In [2]:
import sys

import torch
import pandas as pd
import sklearn as sk

print(f"PyTorch Version: {torch.__version__}")
print()
print(f"Python {sys.version}")
print(f"Pandas {pd.__version__}")
print(f"Scikit-Learn {sk.__version__}")
print("GPU is", "available" if torch.cuda.is_available() else "NOT AVAILABLE")

PyTorch Version: 1.12.0

Python 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:24:02) 
[Clang 11.1.0 ]
Pandas 1.4.0
Scikit-Learn 1.0.2
GPU is NOT AVAILABLE


In [10]:
x = torch.empty(2,2,2,2)
print(x)

tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]])


In [12]:
## random 
x = torch.rand(2,2)
print(x)

tensor([[0.0796, 0.7661],
        [0.0435, 0.3108]])


In [14]:
##zero function 
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [18]:
##one function 
x = torch.ones(2,2, dtype=torch.int)
print(x)
print(x.dtype)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
torch.int32


In [19]:
##passing the datatype 
x = torch.ones(2,2, dtype=torch.int)
print(x)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)


In [20]:
##passing datatype 
x = torch.ones(3,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [26]:
##Construct list in torch 
x = torch.tensor([2.5,3.4,3.5,3.5,6,8])
print(x)
print(x.dtype)

tensor([2.5000, 3.4000, 3.5000, 3.5000, 6.0000, 8.0000])
torch.float32


In [30]:
##basic operations of random number 
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = x+y
print(z)

tensor([[0.2584, 0.4028],
        [0.4094, 0.5789]])
tensor([[0.2110, 0.5141],
        [0.5487, 0.6104]])
tensor([[0.4694, 0.9168],
        [0.9581, 1.1893]])


In [34]:
##basic operations of random number 
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = torch.add(x,y)
print(z)

tensor([[0.9630, 0.0197],
        [0.9759, 0.1129]])
tensor([[0.6163, 0.2270],
        [0.6948, 0.3780]])
tensor([[1.5793, 0.2468],
        [1.6707, 0.4909]])


In [39]:
## Pytroch Multiplication 

x = torch.rand(2,2)
y  = torch.rand(2,2)
print(y)
print(x)
z = x*y 
d = torch.mul(x,y)
print(d)
print(z)

tensor([[0.9615, 0.0524],
        [0.6863, 0.1034]])
tensor([[0.4455, 0.7059],
        [0.0159, 0.2125]])
tensor([[0.4283, 0.0370],
        [0.0109, 0.0220]])
tensor([[0.4283, 0.0370],
        [0.0109, 0.0220]])


In [41]:
##pytroch division operation 
x = torch.rand(2,2)
y = torch.rand(2,2)
z = x/y
d = torch.div(x,y)
print(z)
print(d)

tensor([[23.3417,  0.0822],
        [ 0.4799,  0.0778]])
tensor([[23.3417,  0.0822],
        [ 0.4799,  0.0778]])


In [44]:
### 
x = torch.rand(5,2)
print(x)
print(x[:,1])

tensor([[0.9422, 0.7894],
        [0.3227, 0.2046],
        [0.6114, 0.4518],
        [0.5089, 0.8556],
        [0.6752, 0.1167]])
tensor([0.7894, 0.2046, 0.4518, 0.8556, 0.1167])


In [46]:
## Reshaping tensors 
## using reshape funciton 
x = torch.tensor([1,2,3,4,5,6,7,8])
print(x)
##reshape into 2 dimensional 
reshaped_x = x.reshape(4,2)
print(reshaped_x)

tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [48]:
## Reshaping tensors 
## using reshape funciton 
x = torch.rand(4,4)
print(x)
reshaped_x = x.reshape(-1,8)
print(reshaped_x)
##reshape into 2 dimensional 



tensor([[0.8788, 0.6410, 0.1196, 0.4569],
        [0.4670, 0.9027, 0.0090, 0.8415],
        [0.1427, 0.5439, 0.1586, 0.5283],
        [0.1159, 0.0878, 0.2897, 0.4939]])
tensor([[0.8788, 0.6410, 0.1196, 0.4569, 0.4670, 0.9027, 0.0090, 0.8415],
        [0.1427, 0.5439, 0.1586, 0.5283, 0.1159, 0.0878, 0.2897, 0.4939]])


In [52]:
## converting to numpy to torch tensor 
import numpy as np 
a = torch.ones(5)
b = a.numpy()
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [54]:
## Pytorch Autograd

x = torch.rand(3,requires_grad=True)
print(x)

tensor([0.3590, 0.2395, 0.8692], requires_grad=True)
